language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm install -g serverless
before_install:
- openssl aes-256-cbc -K $encrypted_bd8a98cab2a1_key -iv $encrypted_bd8a98cab2a1_iv
  -in lfpSecret85a5243a0bd4.json.enc -out lfpSecret85a5243a0bd4.json -d
deploy:
  provider: gae
  keyfile: lfpSecret85a5243a0bd4.json
  project: learning-for-purpose
